# For more information: https://laravel.com/docs/sail
services:
    laravel.test:
        container_name: kata-laravel
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                CI_MODE: '${CI_MODE:-local}'
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            CI_MODE: '${CI_MODE:-local}'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            SUPERVISOR_PHP_COMMAND: '/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        container_name: kata-mysql
        image: 'mysql/mysql-server:latest'
        command:
            --sql_mode="NO_ENGINE_SUBSTITUTION"
            --max_connections=1000
            --bind-address=0.0.0.0
            --log_output=FILE
            --slow_query_log=ON
            --long_query_time=0
            --slow_query_log_file=/var/log/mysql/mysql-slow.log
            --log_slow_admin_statements=ON
            --log_slow_slave_statements=ON
            --performance_schema=ON
            --innodb_monitor_enable=all
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'laravel-kata-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        container_name: kata-redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'laravel-kata-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    percona-pmm:
        container_name: kata-percona-pmm
        image: percona/pmm-server:2
        platform: linux/amd64
        ports:
            - ${PMM_PORT_HTTP:-81}:80
            - ${PMM_PORT_HTTPS:-444}:443
        networks:
            - sail
        volumes:
            - percona-pmm-data:/srv
        restart: always
networks:
    sail:
        driver: bridge
volumes:
    laravel-kata-mysql:
        driver: local
    laravel-kata-redis:
        driver: local
    percona-pmm-data:
        driver: local
