# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        container_name: kata-laravel
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                CI_MODE: '${CI_MODE}'
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            CI_MODE: '${CI_MODE}'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - laravel-kata
        depends_on:
            - mysql
            - redis
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "curl", "http://localhost/" ]
            retries: 3
            timeout: 5s
    mysql:
        container_name: kata-mysql
        image: 'mysql/mysql-server:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'laravel-kata-mysql:/var/lib/mysql'
        networks:
            - laravel-kata
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        container_name: kata-redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'laravel-kata-redis:/data'
        networks:
            - laravel-kata
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    laravel-kata:
        driver: bridge
volumes:
    laravel-kata-mysql:
        driver: local
    laravel-kata-redis:
        driver: local
