# For more information: https://laravel.com/docs/sail
# - https://medium.com/@nairgirish100/k6-with-docker-compose-influxdb-grafana-344ded339540
version: '3'

networks:
    laravel-kata:
        driver: bridge
    laravel-kata-k6:
        driver: bridge
    laravel-kata-grafana:
        driver: bridge

services:
    laravel.test:
        container_name: kata-laravel
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                CI_MODE: '${CI_MODE}'
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            CI_MODE: '${CI_MODE}'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - laravel-kata
        depends_on:
            - mysql
            - redis
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "curl", "http://localhost/" ]
            retries: 3
            timeout: 5s
    mysql:
        container_name: kata-mysql
        image: 'mysql/mysql-server:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'laravel-kata-mysql:/var/lib/mysql'
        networks:
            - laravel-kata
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        container_name: kata-redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'laravel-kata-redis:/data'
        networks:
            - laravel-kata
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    influxdb:
        container_name: kata-influxdb
        image: influxdb:1.8
        networks:
            - laravel-kata-k6
            - laravel-kata-grafana
        ports:
            - "8086:8086"
        environment:
            - INFLUXDB_DB=k6

    grafana:
        container_name: kata-grafana
        image: grafana/grafana:latest
        networks:
            - laravel-kata-grafana
        ports:
            - "3001:3000"
        environment:
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_BASIC_ENABLED=false
        volumes:
            - 'laravel-kata-grafana:/etc/grafana/provisioning/'

    k6:
        image: grafana/k6:latest
        platform: linux/amd64
        networks:
            - laravel-kata-k6
        ports:
            - "6565:6565"
        environment:
            - K6_OUT=influxdb=http://influxdb:8086/k6
        volumes:
            - ./bin/k6:/scripts

volumes:
    laravel-kata-mysql:
        driver: local
    laravel-kata-redis:
        driver: local
    laravel-kata-grafana:
        driver: local
