#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# TODO: Figure out how to make linting seamless
# - Auto lint staged files only
# - Run tests
# - If passed, auto add changed before commit

# Hacked for now
./vendor/bin/sail pint
git add --all

npm test

# lint staged files
# lint-staged

# run tests
# npm test
